# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinfo',
            name='CGST',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='Discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='Duedate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='HSN',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='Qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='Rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='SGST',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='Taxable_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='Units',
            field=models.IntegerField(null=True),
        ),
    ]
