# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170929_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinfo',
            name='VendorName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
