# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170930_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinfo',
            name='HSN',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseinfo',
            name='ItemDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='purchaseinfo',
            name='Refernce',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinfo',
            name='VendorName',
            field=models.CharField(max_length=50),
        ),
    ]
