# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170930_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinfo',
            name='Refernce',
            field=models.CharField(default='Null', max_length=30, null=True),
        ),
    ]
