# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170930_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinfo',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 9, 30, 7, 44, 59, 239455, tzinfo=utc)),
        ),
    ]
