# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 07:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_purchaseinfo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinfo',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 9, 30, 7, 47, 1, 277279)),
        ),
    ]
