# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_purchaseinfo_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTkey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstrate', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HSN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HSN', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseinfo',
            name='HSN',
        ),
        migrations.AlterField(
            model_name='purchaseinfo',
            name='Rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GSTkey'),
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='HSNa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.HSN'),
        ),
    ]
