# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171003_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinfo',
            name='date',
            field=models.DateField(null=True, verbose_name=' Invoice was made on:'),
        ),
        migrations.AlterField(
            model_name='purchaseinfo',
            name='Duedate',
            field=models.DateField(null=True, verbose_name='Time which date of bill going to be invalid'),
        ),
    ]
